


        #Foodstuffs


          [fwi_spellfruit_mocktail_bundle]
          description = "An unfinished spell fruit mocktail. Use to stir and finish it."
          icon_sprite = "spr_ui_item_food_fwi_spellfruit_mocktail"
          name = "Unfinished Spell Fruit Mocktail"
          overwrites_other_mod = false
          stars = 5
          crafting_level_requirement = 45
          kitchen_tier_requirement = 3
          tags = [
            "cold_drink"
          ]
          item_bundle = [{ fwi_spellfruit_mocktail = 1 }]

                    recipe = [
            { count = 1, item = "essence_blossom" },

            { count = 1, item = "lemon" },

            { count = 1, item = "rock_salt" },

            { count = 1, item = "spell_fruit" },

            { hours = 0, minutes = 60 }
          ]
          value = { bin = "self.recipe * 1.1" }



        [fwi_spellfruit_mocktail]
    description = "A mocktail made from spell fruit and essence blossoms, consume for 50 essence."
    icon_sprite = "spr_ui_item_food_fwi_spellfruit_mocktail"
    name = "Spell Fruit Mocktail"
    overwrites_other_mod = false

          tags = [
            "essence_stone",
            "material"
          ]
          essence_charge = 0
          recipe_is_default = false

          recipe = [
            { essence = 50 },

            { count = 1, item = "essence_blossom" },

            { count = 1, item = "lemon" },

            { count = 1, item = "rock_salt" },

            { count = 1, item = "spell_fruit" },

            { hours = 0, minutes = 60 }
          ]
          value = { store = 420, bin = "self.recipe * 1.1" }
        


        #DEUG CHEATS LOL

                [fwi_debug_gear_bundle]
          description = "this is for debug purposes [Ari], hence the bad grammer"
          icon_sprite = "spr_ui_item_equipment_fwi_demon_forged_shorts"
          name = "debug shit"
          overwrites_other_mod = false
          stars = 5
          crafting_level_requirement = 45
          kitchen_tier_requirement = 3
          item_bundle = [
            { fwi_demon_forged_boots = 1 },

            { fwi_sword_demon_forged = 1 },

            { fwi_demon_forged_thingy = 1 },
            
            { fwi_demon_forged_chestplate = 1 },

            { fwi_demon_forged_helm = 1 },
            
            { fwi_demon_forged_panties = 1 }
          ]

          value = { store = 1, bin = 9999 }
