
  [fwi_sword_demon_forged]
    description = "A sword forged in Demonic fire, although this one is a knockoff as it was made in a Dragon Forge..."
    damage = 32
    icon_sprite = "spr_ui_item_fwi_demon_forged_sword"
    name  "Demon-Forged Blade"
    quality = "tier6"
    recipe_is_default = true
    default_infusion = "instant_kill"
    overwrites_other_mod = false
    tags = [
      "sword",
      "blacksmithing",
      "weapon"
    ]
    crafting_level_requirement = 60
    recipe = [
      { count = 100, item = "voidite" },

      { count = 10, item = "mistril_ingot" },

      { count = 1, item = "perfect_pink_diamond" },

      { count = 5, item = "fwi_electrum_ingot" },

      { hours = 1, minutes = 0 }
    ]
    value = { bin = "self.recipe*1.5", store = 666666 }



  [fwi_electrum_ingot]  
    description = "An ingot of pure electrum alloy."
    icon_sprite = "spr_ui_item_fwi_electrum_ingot"
    name = "Electrum Ingot"
    overwrites_other_mod = false
    tags = [
      "ingot",
      "blacksmithing"
    ]
    crafting_level_requirement = 10
    recipe_is_default = true
    recipe = [
      { count = 3, item = "ore_gold" },

      { count = 3, item = "ore_silver" },

      { count = 3, item = "ore_copper" },

      { count = 1, item = "ore_mistril" },

      { hours = 0, minutes = 20 }
    ]
    value = { bin = "self.recipe*1.2", store = 5000 }


        #Foodstuffs


          [fwi_spellfruit_mocktail_bundle]
          description = "An unfinished spell fruit mocktail. Use to stir and finish it."
          icon_sprite = "spr_ui_item_fwi_spellfruit_mocktail_bundle"
          name = "Unfinished Spell Fruit Mocktail"
          overwrites_other_mod = false
          stars = 5
          crafting_level_requirement = 45
          kitchen_tier_requirement = 3
          tags = [
            "cold_drink"
          ]
          item_bundle = [{ fwi_spellfruit_mocktail = 1 }]

                    recipe = [
            { count = 1, item = "essence_blossom" },

            { count = 1, item = "lemon" },

            { count = 1, item = "rock_salt" },

            { count = 1, item = "spell_fruit" },

            { hours = 0, minutes = 60 }
          ]
          value = { bin = "self.recipe * 1.1" }



        [fwi_spellfruit_mocktail]
    description = "A mocktail made from spell fruit and essence blossoms, consume for 50 essence."
    icon_sprite = "spr_ui_item_fwi_spellfruit_mocktail"
    name = "Spell Fruit Mocktail"
    overwrites_other_mod = false

          tags = [
            "essence_stone",
            "material"
          ]
          essence_charge = 0
          recipe_is_default = false

          recipe = [
            { essence = 50 }

            { count = 1, item = "essence_blossom" },

            { count = 1, item = "lemon" },

            { count = 1, item = "rock_salt" },

            { count = 1, item = "spell_fruit" },

            { hours = 0, minutes = 60 }
          ]
          value = { store = 420, bin = "self.recipe * 1.1" }
        


        #DEUG CHEATS LOL

                [fwi_debug_gear_bundle]
          description = "this is for debug purposes [Ari], hence the bad grammer"
          icon_sprite = "spr_ui_item_fwi_debug_gear_bundle"
          name = "debug shit"
          overwrites_other_mod = false
          stars = 5
          crafting_level_requirement = 45
          kitchen_tier_requirement = 3
          item_bundle = [
            { fwi_demon_forged_boots = 1 },

            { fwi_sword_demon_forged = 1 },

            { fwi_demon_forged_thingy = 1 },
            
            { fwi_demon_forged_chestplate = 1 },

            { fwi_demon_forged_helm = 1 },
            
            { fwi_demon_forged_panties = 1 }
          ]

          value = { store = 1, bin = 9999 }
