# The inventory item that places the Example Crafting Station furniture.
[fwi_demon_forge]
	icon_sprite = "spr_ui_item_crafting_table"
	name = "Demon Forge"
	description = "An example modded crafting station. Place it, then interact to craft."
	value = { bin = 80, store = 800 }
	object = "fwi_demon_forge"
	tags = ["furniture", "misc_furniture"]
