# The inventory item that places the Example Crafting Station furniture.
[fwi_demon_forge]
	icon_sprite = "spr_ui_item_crafting_table"
	name = "Demon Forge"
	description = "A demon-forge, used for crafting various items that require interdiciplinary skill and unique equipment."
	value = { bin = 80, store = 800 }
	object = "fwi_demon_forge"
	tags = ["furniture", "misc_furniture"]
