         [fwi_demon_forged_chestplate]
           description = "A chestplate forged in Demonic fire, although this one is a knockoff as it was made in a Dragon Forge..."
           defense = 8
          icon_sprite = "spr_ui_item_equipment_fwi_demon_forged_chestplate"
          name = "Demon-Forged Chestplate"
          recipe_is_default = true
          overwrites_other_mod = false
          default_infusion = "demonic1"
          tags = [
            "chest",
            "armor",
            "blacksmithing",
            "mistril_armor",
            "fwi_demon_forge",
            "glow_armor"
          ]
          crafting_level_requirement = 60
          recipe = [
            { hours = 0, minutes = 50 },

            { count = 10, item = "mistril_ingot" },

            { count = 1, item = "perfect_pink_diamond" },

            { count = 5, item = "fwi_electrum_ingot" }
          ]

          value = { bin = "self.recipe*1.5", store = 66666}



                  [fwi_demon_forged_helm] 
          description = "An enchanted essence blossom empowered in Demonic fire, although this one is a knockoff as it was made in a Dragon Forge..."
          defense = 8
          icon_sprite = "spr_ui_item_equipment_fwi_enchanted_essence_blossom"
          name = "Demon-Forged Essence Blossom"
          recipe_is_default = true
          overwrites_other_mod = false
          default_infusion = "demonic1"
          tags = [
            "head",
            "armor",
            "blacksmithing",
            "mistril_armor",
            "fwi_demon_forge",
            "glow_armor"
          ]
          crafting_level_requirement = 60
          recipe = [
            { hours = 0, minutes = 50 },

            { count = 10, item = "mistril_ingot" },

            { count = 1, item = "essence_blossom" },

            { count = 5, item = "fwi_electrum_ingot" }
          ]

          value = { bin = "self.recipe*1.5", store = 66666 }



                  [fwi_demon_forged_boots]
          description = "A pair of boots forged in Demonic fire, although these ones are knockoffs as they were made in a Dragon Forge..."
          defense = 8
          icon_sprite = "spr_ui_item_equipment_fwi_demon_forged_boots"
          name = "Demon-Forged Boots"
          recipe_is_default = true
          overwrites_other_mod = false
          default_infusion = "demonic1"
          tags = [
            "boots",
            "armor",
            "blacksmithing",
            "mistril_armor",
            "fwi_demon_forge",
            "glow_armor"
          ]
          crafting_level_requirement = 60
          recipe = [
            { hours = 0, minutes = 50 },

            { count = 10, item = "mistril_ingot" },

            { count = 25, item = "ore_pink_diamond" },

            { count = 5, item = "fwi_electrum_ingot" }
          ]

          value = { bin = "self.recipe*1.5", store = 66666 }



                  [fwi_demon_forged_thingy]
          description = "A... Something forged in Demonic fire, although this one is probably a knockoff as it was made in a Dragon Forge..."
          defense = 8
          icon_sprite = "spr_ui_item_equipment_fwi_demon_forged_thingy"
          name = "Demon-Forged Thingy"
          recipe_is_default = true
          overwrites_other_mod = false
          default_infusion = "demonic1"
          tags = [
            "accessory",
            "armor",
            "blacksmithing",
            "mistril_armor",
            "fwi_demon_forge",
            "glow_armor"
          ]
          crafting_level_requirement = 60
          recipe = [
            { hours = 0, minutes = 50 },

            { count = 10, item = "mistril_ingot" },

            { count = 1, item = "hardened_essence" },

            { count = 5, item = "fwi_electrum_ingot" }
          ]

          value = { bin = "self.recipe*1.5", store = "self.recipe*2500" }



                  [fwi_demon_forged_panties]
          description = "Some luxurious pink 'shorts' trimmed in gold, and forged in Demonic fire, although these ones are knockoffs as they were made in a Dragon Forge..."
          defense = 8
          icon_sprite = "spr_ui_item_equipment_fwi_demon_forged_shorts"
          name = "Demon-Forged 'Shorts'"
          recipe_is_default = true
          overwrites_other_mod = false
          default_infusion = "demonic1"
          tags = [
            "legs",
            "armor",
            "blacksmithing",
            "mistril_armor",
            "fwi_demon_forge",
            "glow_armor"
          ]
          crafting_level_requirement = 60
          recipe = [
            { hours = 0, minutes = 50  },

            { count = 10, item = "mistril_ingot" },

            { count = 20, item = "gold_ingot" },

            { count = 5, item = "fwi_electrum_ingot" }
          ]

          value = { bin = "self.recipe*1.5", store = 69420 }
