
[[blacksmith.categories]]
    icon = "spr_ui_item_perfect_pink_diamond"
    constant_stock = [
        { recipe_scroll = "fwi_sword_demon_forged" },
        { recipe_scroll = "fwi_electrum_ingot" },
        { recipe_scroll = "fwi_demon_forged_helm" },
        { recipe_scroll = "fwi_demon_forged_boots" },
        { recipe_scroll = "fwi_demon_forged_thingy" },
        { recipe_scroll = "fwi_demon_forged_panties" },
        { recipe_scroll = "fwi_demon_forged_chestplate" },

    ]

[[inn.categories]]
    icon = "spr_ui_store_category_icon_cooking_recipes"
    constant_stock = [ 
        { recipe_scroll = "fwi_spellfruit_mocktail_bundle" },
    ]

#Debug Items

[[balor.categories]]
    icon = "spr_ui_store_category_icon_materials"
    constant_stock = [
        { item = "fwi_debug_gear_bundle" },
    ]

  

